server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: teams-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/teams/**

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG